In [8]:
import pandas as pd

In [9]:
df=pd.read_excel("D:/python_datascience/data sets/examples/catalog.xlsx")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'D:/python_datascience/data sets/examples/catalog.xlsx'

In [10]:
df.info()

NameError: name 'df' is not defined

In [ ]:
df["date"].mode()

In [4]:
# checking date column missing values 
df["date"].isnull().sum()

NameError: name 'df' is not defined

In [5]:
# fill missing values in date column
df["date"].fillna(df["date"].mode()[0],inplace=True)

NameError: name 'df' is not defined

In [141]:
df["date"].isnull().sum()

0

In [142]:
df.isnull().sum()

id                         0
date                       0
time                    1064
continent_code          1529
country_name               0
country_code               0
state/province             1
population                 0
city/town                  4
distance                   1
location_description    1142
latitude                   1
longitude                  1
geolocation                1
hazard_type                0
landslide_type             1
landslide_size             1
trigger                    2
storm_name              1561
injuries                1178
fatalities               247
source_name              821
source_link              100
dtype: int64

In [143]:
df.drop(columns=["continent_code","location_description","source_link","source_name","fatalities","storm_name","injuries","city/town","distance","latitude","longitude","landslide_size","trigger","geolocation"],inplace=True)

In [144]:
df.head()

id                 date   time   country_name country_code state/province  \
0  34  2007-02-03 00:00:00  Night  United States           US       Virginia   
1  42              3/22/07    NaN  United States           US           Ohio   
2  56  2007-06-04 00:00:00    NaN  United States           US   Pennsylvania   
3  59              4/14/07    NaN         Canada           CA         Quebec   
4  61              4/15/07    NaN  United States           US       Kentucky   

   population hazard_type      landslide_type  
0       16000   Landslide           Landslide  
1       17288   Landslide           Landslide  
2       15930   Landslide           Landslide  
3       42786   Landslide  Riverbank collapse  
4        6903   Landslide           Landslide

In [145]:
df["landslide_type"].fillna(df["landslide_type"].mode()[0],inplace=True)

In [146]:
# converting date to datetime datatype 
df["date"]=pd.to_datetime(df["date"])

In [147]:
df.dtypes

id                         int64
date              datetime64[ns]
time                      object
country_name              object
country_code              object
state/province            object
population                 int64
hazard_type               object
landslide_type            object
dtype: object

In [148]:
## now it shows date column has been converted 

In [149]:
from datetime import datetime as dt

In [150]:
# creating a new column name year and extarcting year from date column
df["year"]=df.date.dt.year
df.head()

id       date   time   country_name country_code state/province  \
0  34 2007-02-03  Night  United States           US       Virginia   
1  42 2007-03-22    NaN  United States           US           Ohio   
2  56 2007-06-04    NaN  United States           US   Pennsylvania   
3  59 2007-04-14    NaN         Canada           CA         Quebec   
4  61 2007-04-15    NaN  United States           US       Kentucky   

   population hazard_type      landslide_type  year  
0       16000   Landslide           Landslide  2007  
1       17288   Landslide           Landslide  2007  
2       15930   Landslide           Landslide  2007  
3       42786   Landslide  Riverbank collapse  2007  
4        6903   Landslide           Landslide  2007

In [151]:
df["year"].unique()

array([2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016],
      dtype=int64)

In [152]:
## extracting month
df["month"]=df.date.dt.month
df.head()

id       date   time   country_name country_code state/province  \
0  34 2007-02-03  Night  United States           US       Virginia   
1  42 2007-03-22    NaN  United States           US           Ohio   
2  56 2007-06-04    NaN  United States           US   Pennsylvania   
3  59 2007-04-14    NaN         Canada           CA         Quebec   
4  61 2007-04-15    NaN  United States           US       Kentucky   

   population hazard_type      landslide_type  year  month  
0       16000   Landslide           Landslide  2007      2  
1       17288   Landslide           Landslide  2007      3  
2       15930   Landslide           Landslide  2007      6  
3       42786   Landslide  Riverbank collapse  2007      4  
4        6903   Landslide           Landslide  2007      4

In [153]:
df["month"].unique()

array([ 2,  3,  6,  4,  5,  1,  8,  7,  9, 11, 12, 10], dtype=int64)

In [154]:
## extracting month name
df["m_name"]=df.date.dt.month_name()
df["m_name"].unique()

array(['February', 'March', 'June', 'April', 'May', 'January', 'August',
       'July', 'September', 'November', 'December', 'October'],
      dtype=object)

In [155]:
## extracting day
df["day"]=df.date.dt.day
df["day"].unique()

array([ 3, 22,  4, 14, 15, 20, 24, 21, 27,  7, 13,  8, 17, 18, 19, 23,  9,
       28, 10, 29, 31, 11, 30, 12, 16,  1,  2, 25,  5,  6, 26],
      dtype=int64)

In [156]:
## extracting day_name
df["day_name"]=df.date.dt.day_name()
df["day_name"].unique()

array(['Saturday', 'Thursday', 'Monday', 'Sunday', 'Friday', 'Tuesday',
       'Wednesday'], dtype=object)

In [157]:
## extracting week of the year
df["d_week"]=df.date.dt.dayofweek
df["d_week"].unique()

array([5, 3, 0, 6, 4, 1, 2], dtype=int64)

In [158]:
## extracting week of the year
df["week_no"]=df.date.dt.week
df["week_no"].unique()

C:\Users\acer\AppData\Local\Temp\ipykernel_4868\2766464238.py:2: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated. Please use Series.dt.isocalendar().week instead.
  df["week_no"]=df.date.dt.week


array([ 5, 12, 23, 15, 16, 17, 21, 26,  1, 14, 32, 28, 30, 36, 45, 33, 34,
        2,  6, 10, 19, 38, 39, 37, 50, 41, 42, 43, 44, 46, 48, 51, 22, 27,
       18,  9, 40, 11, 13, 49, 25, 29, 31, 35, 24, 47, 52,  4, 20, 53,  3,
        7,  8], dtype=int64)

In [159]:
### extracting weekend
import numpy as np
df["date is weekend"]=np.where(df["day_name"].isin(["Sunday","Saturday"]),1,0)
df["date is weekend"]

0       1
1       0
2       0
3       1
4       1
       ..
1688    1
1689    0
1690    0
1691    0
1692    0
Name: date is weekend, Length: 1693, dtype: int32

In [160]:
### extracting quarter

df["quarter"]=df.date.dt.quarter
df["quarter"].unique()

array([1, 2, 3, 4], dtype=int64)

In [161]:
df.columns

Index(['id', 'date', 'time', 'country_name', 'country_code', 'state/province',
       'population', 'hazard_type', 'landslide_type', 'year', 'month',
       'm_name', 'day', 'day_name', 'd_week', 'week_no', 'date is weekend',
       'quarter'],
      dtype='object')

In [162]:
#df["time"].fillna(df["time"].mode()[0],inplace=True)

In [163]:
#df["time"].dtype

In [164]:
#df['time'].unique()

In [166]:
### current date
import datetime
today=datetime.datetime.today()
today

datetime.datetime(2022, 11, 17, 15, 29, 53, 159455)

In [167]:
today-df["date"]

0      5766 days 15:29:53.159455
1      5719 days 15:29:53.159455
2      5645 days 15:29:53.159455
3      5696 days 15:29:53.159455
4      5695 days 15:29:53.159455
                  ...           
1688   2685 days 15:29:53.159455
1689   2460 days 15:29:53.159455
1690   2459 days 15:29:53.159455
1691   2456 days 15:29:53.159455
1692   2479 days 15:29:53.159455
Name: date, Length: 1693, dtype: timedelta64[ns]

In [170]:
np.round((today-df["date"])/np.timedelta64(1,"M"),0)

0       189.0
1       188.0
2       185.0
3       187.0
4       187.0
        ...  
1688     88.0
1689     81.0
1690     81.0
1691     81.0
1692     81.0
Name: date, Length: 1693, dtype: float64

In [169]:
df["time"]=df["date"].dt.time

array([datetime.time(0, 0)], dtype=object)

In [173]:
## fetch how many landslides  type in each year
df.groupby(["year"])["landslide_type"].value_counts().sort_values(ascending=False).head(5)


year  landslide_type
2010  Landslide         179
2015  Landslide         154
2011  Landslide         154
2010  Mudslide          132
2013  Mudslide          127
Name: landslide_type, dtype: int64

In [73]:
# fetching month from date

In [74]:
df["month"]=df.date.dt.month
df

id       date      time   country_name country_code  state/province  \
0       34 2007-02-03  00:00:00  United States           US        Virginia   
1       42 2007-03-22  00:00:00  United States           US            Ohio   
2       56 2007-06-04  00:00:00  United States           US    Pennsylvania   
3       59 2007-04-14  00:00:00         Canada           CA          Quebec   
4       61 2007-04-15  00:00:00  United States           US        Kentucky   
...    ...        ...       ...            ...          ...             ...   
1688  7535 2015-07-12  00:00:00  United States           US  North Carolina   
1689  7537 2016-02-22  00:00:00  United States           US   West Virginia   
1690  7539 2016-02-23  00:00:00  United States           US   West Virginia   
1691  7540 2016-02-26  00:00:00  United States           US   West Virginia   
1692  7541 2016-02-03  00:00:00  United States           US         Vermont   

      population                                geolocation hazard_type  \
0          16000  (38.600900000000003, -77.268199999999993)   Landslide   
1          17288  (40.517499999999998, -81.430499999999995)   Landslide   
2          15930             (40.4377, -79.915999999999997)   Landslide   
3          42786  (45.322600000000001, -73.777100000000004)   Landslide   
4           6903  (37.432499999999997, -82.493099999999998)   Landslide   
...          ...                                        ...         ...   
1688        1646  (35.221899999999998, -82.322599999999994)   Landslide   
1689       51400  (38.398699999999998, -81.584800000000001)   Landslide   
1690        2406             (37.409599999999998, -81.4268)   Landslide   
1691        1048  (37.501100000000001, -81.109300000000005)   Landslide   
1692        2066             (43.4771, -72.406599999999997)   Landslide   

          landslide_type  year  month    m_name  day   day_name  d_week  \
0              Landslide  2007      2  February    3   Saturday       5   
1              Landslide  2007      3     March   22   Thursday       3   
2              Landslide  2007      6      June    4     Monday       0   
3     Riverbank collapse  2007      4     April   14   Saturday       5   
4              Landslide  2007      4     April   15     Sunday       6   
...                  ...   ...    ...       ...  ...        ...     ...   
1688            Rockfall  2015      7      July   12     Sunday       6   
1689            Mudslide  2016      2  February   22     Monday       0   
1690           Landslide  2016      2  February   23    Tuesday       1   
1691            Rockfall  2016      2  February   26     Friday       4   
1692            Rockfall  2016      2  February    3  Wednesday       2   

      week_no  date is weekend  quarter  
0           5                1        1  
1          12                0        1  
2          23                0        2  
3          15                1        2  
4          15                1        2  
...       ...              ...      ...  
1688       28                1        3  
1689        8                0        1  
1690        8                0        1  
1691        8                0        1  
1692        5                0        1  

[1693 rows x 19 columns]

In [75]:
df["month"]

0       2
1       3
2       6
3       4
4       4
       ..
1688    7
1689    2
1690    2
1691    2
1692    2
Name: month, Length: 1693, dtype: int64

In [76]:
df.isnull().sum()

id                 0
date               0
time               0
country_name       0
country_code       0
state/province     1
population         0
geolocation        1
hazard_type        0
landslide_type     0
year               0
month              0
m_name             0
day                0
day_name           0
d_week             0
week_no            0
date is weekend    0
quarter            0
dtype: int64

In [77]:
df.groupby(["month"])["landslide_size"].value_counts()

KeyError: 'Column not found: landslide_size'

In [ ]:
#find the country name having maximum number of landslides

df.groupby(["country_name"])["landslide_type"].agg("count").sort_values(ascending=False)

In [ ]:
## getting current date and time
dt.now()

## or 

In [ ]:
dt.today()

In [ ]:
dt.fromtimestamp(1630)

In [ ]:
from datetime import date
x=date(2022,10,28).isocalendar()
x
# it returns the week no and week day from begening of the year  ## weekno from ist january

In [ ]:
#strftime() and strptime()
# difference between these two


In [ ]:
for i in df["date"]:
    s=date.strftime(i,"%d/%m/%y")
    print(type(s),s)

In [ ]:
s

In [ ]:
from datetime import datetime as dt

In [ ]:
d=dt.strptime(s,"%d/%m/%y")
print(d)

In [ ]:
type(d)